use_frameworks!
platform :ios, '8.3'

target 'MXLCalendarManagerSwift_Example' do
  pod 'MXLCalendarManagerSwift', :git => 'https://github.com/ramonvasc/MXLCalendarManagerSwift.git'

  target 'MXLCalendarManagerSwift_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
