use_frameworks!
platform :ios, '13'

target 'MXLCalendarManagerSwift_Example' do
  pod 'MXLCalendarManagerSwift', :git => 'https://github.com/ramonvasc/MXLCalendarManagerSwift.git', :branch => 'master'

  target 'MXLCalendarManagerSwift_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
